name: GitHub Self-Updating Repository Demo

on:
  schedule:
    # 每 5 分钟运行一次
    - cron: '*/5 * * * *'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Modify date and time (CST)
        run: |
          TZ='Asia/Shanghai' date > README.md
          cat README.md
        timeout-minutes: 2

      - name: Push to repository
        run: |
          git config --global user.name "amulil"
          git config --global user.email "amulil@users.noreply.github.com"
          now=$(TZ='Asia/Shanghai' date)
          git add -A
          git commit -m "Auto Push on $now"
          # 拉取远程更改并合并
          git pull origin main --rebase
          # 推送到远程仓库
          git push
